Repository shoppad/mesa-templates, pull requests merged in 2020-04, with the labels that each got.

#124 Send product to another sotre: Add check for product ID
  shopify/product/send-to-another-store/out-delete-shopify-product.js
  shopify/product/send-to-another-store/out-update-shopify-product.js
Labels: Ready to merge

#125 Scheduled Product Price Change
  shopify/product/scheduled-product-price-change/README.md
  shopify/product/scheduled-product-price-change/get-products-json.js
  shopify/product/scheduled-product-price-change/mesa.json
  shopify/product/scheduled-product-price-change/update-product-transform.js
Labels: QA'd

#123 Mesa Image templates
  shopify/order/remove-background-from-uploadery-images/mesa.json
  shopify/order/remove-background-from-uploadery-images/shopify-update-order-transform.js
  shopify/order/remove-background-from-uploadery-images/transform.js
  shopify/order/send-uploadery-file-to-cloudinary-transform/README.md
  shopify/order/send-uploadery-file-to-cloudinary-transform/in-shopify-order-create.js
  shopify/order/send-uploadery-file-to-cloudinary-transform/mesa.json
  shopify/order/send-uploadery-file-to-cloudinary-transform/out-send-to-cloudinary.js
  shopify/order/send-uploadery-file-to-cloudinary-transform/out-update-shopify-order-notes.js
  shopify/product/add-image-colors-to-product-as-tags/README.md
  shopify/product/add-image-colors-to-product-as-tags/in-shopify-product-webhook.js
  shopify/product/add-image-colors-to-product-as-tags/mesa.json
  shopify/product/add-image-colors-to-product-as-tags/out-update-shopify-product.js
  shopify/product/add-image-colors-to-products-as-tags/mesa.json
  shopify/product/add-image-colors-to-products-as-tags/shopify-update-product-transform.js
Labels: QA'd, Ready to merge

#128 Test templates: refactor structure
  tests/kitchen_sink/README.md
  tests/kitchen_sink/in-kitchen-sink-ftp.js
  tests/kitchen_sink/in-kitchen-sink.js
  tests/kitchen_sink/mesa.json
  tests/kitchen_sink/out-kitchen-sink-vo.js
  tests/shopify_product_update/README.md
  tests/shopify_product_update/mesa.json
  tests/shopify_product_update/transform.js
  tests/shopify_tokens/mesa.json
  tests/shopify_tokens/shopify_update_customer_transform.js
Labels: Ready to merge
