Repository shoppad/mesa-templates, pull requests merged in 2021-11, with the labels that each got.

#285 Shopify Order Line Item Properties to Notes: preserve existing notes
  shopify/order/add_line_item_properties_to_notes/mesa.json
Labels: QA'd, Ready to merge

#278 Send Order To Google Sheets Document (Simple Version)
  shopify/order/send_to_google_sheets_document/mesa.json
Labels: QA'd

#286 IO Product Purchased to Email - simplify
  infiniteoptions/order/send_email/mesa.json
Labels: QA'd, Ready to merge

#287 Send Email when IO product purchased: updated description
  infiniteoptions/order/send_email/mesa.json
Labels: Ready to merge

#289 Mesa: fix input action for high risk order templates
  shopify/order/send_high_risk_orders_to_slack/mesa.json
  shopify/order/send_high_risk_orders_to_sms/mesa.json
Labels: Ready to merge
