Repository shoppad/mesa-templates, pull requests merged in 2021-08, with the labels that each got.

#255 Shopify app custom routes
  shopify/order/add_free_product_to_new_customer_first_order/custom.js
  shopify/order/add_free_product_to_new_customer_first_order/mesa.json
  shopify/order/edit_add_product/README.md
  shopify/order/edit_add_product/custom.js
  shopify/order/edit_add_product/mesa.json
Labels: Ready to QA

#251 Adding infiniteoptions/order/yotpo_loyalty_set_birthday template
  infiniteoptions/order/yotpo_loyalty_set_birthday/custom.js
  infiniteoptions/order/yotpo_loyalty_set_birthday/mesa.json
Labels: QA'd

#249 Adding shopify/order/manually_approve_funds_capture template
  shopify/order/manually_approve_funds_capture/custom.js
  shopify/order/manually_approve_funds_capture/mesa.json
Labels: QA'd

#250 Adding infiniteoptions/order/track_klaviyo_event template
  infiniteoptions/order/track_klaviyo_event/mesa.json
Labels: QA'd

#252 Adding shopify/order/approve_thank_you_email template
  shopify/order/approve_thank_you_email/mesa.json
Labels: QA'd, Ready to merge

#258 Start a Return with Mesa Forms - add order_id default value
  form/shopify_order_return/mesa.json
Labels: Ready to merge

#257 Adding Save a Customer's Date of Birth to a Yotpo Loyalty Customer template
  form/yotpo_loyalty_customer_dob/mesa.json
Labels: QA'd

#259 Update Google sheets templates
  infiniteoptions/order/add_line_items_to_google_sheet/README.md
  infiniteoptions/order/add_line_items_to_google_sheet/mesa.json
  shopify/customer/add_to_google_sheets_document/README.md
  shopify/customer/add_to_google_sheets_document/mesa.json
  shopify/order/send_to_google_sheets_document/custom.js
  shopify/order/send_to_google_sheets_document/mesa.json
  uploadery/order/add_line_items_to_google_sheet/README.md
  uploadery/order/add_line_items_to_google_sheet/mesa.json
Labels: QA'd

#261 Fixing the order_note token in Add Line Item Properties to Order Notes template
  shopify/order/add_line_item_properties_to_notes/mesa.json
Labels: QA'd

#262 Mesa / update order report template with new HTML email
  shopify/order/send_order_report_card_email/mesa.json
Labels: QA'd, Ready to merge
