Repository shoppad/mesa-templates, pull requests merged in 2021-06, with the labels that each got.

#222 Fosdick template: account for paypal sourced payments
  shopify/order/send_to_fosdick_fulfillment/out_create_fosdick_order.js
Labels: Ready to merge

#224 Send an SMS Message if a Customer Places a Fraudulent Order
  shopify/order/send_high_risk_orders_to_sms/mesa.json
Labels: QA'd

#223 Trigger custom code from a Shopify Flow workflow
  shopify/flow/send_to_custom_code/mesa.json
Labels: QA'd

#226 Trigger a Shopify Flow workflow from any service
  webhook/send_to_flow/mesa.json
Labels: Ready to QA

#228 shopify/product/update_when_out_of_stock
  shopify/product/update_when_out_of_stock/custom.js
  shopify/product/update_when_out_of_stock/mesa.json
Labels: QA'd

#215 Adding tracktor/order/refund_shipping_cost template
  tracktor/order/refund_shipping_cost/mesa.json
Labels: QA'd

#221 Adding daily_export_to_google_sheets
  shopify/order/daily_export_to_google_sheets/mesa.json
Labels: QA'd

#231 Send daily TikTok Ad Group summary report to Google Sheets
  tiktok/reports/send_daily_adgroup_summary_report/mesa.json
Labels: QA'd, Ready to merge

#230 Create a Facebook product when tagged Shopify product is created
  shopify/product/create_facebook_product/mesa.json
Labels: QA'd, Ready to merge
