Repository shoppad/mesa-templates, pull requests merged in 2021-04, with the labels that each got.

#199 Stamped.io: Negative review to customer email template
  stamped_io/review/send_negative_review_to_customer_email/mesa.json
Labels: QA'd, Ready to merge

#205 'Default' template: Send Order Report Card Email
  shopify/order/send_order_report_card_email/compile_order_data.js
  shopify/order/send_order_report_card_email/mesa.json
Labels: Ready to merge

#210 Salesforce: fix errant comment in pricebookentry mapping
  shopify/product/send_to_salesforce_product_and_pricebook_entry/salesforce_create_pricebook_entry_transform.js
Labels: Ready to merge

#209 Updating templates to use non-script based virtual outputs
  shopify/draft_order/remove_after_thirty_days/mesa.json
  shopify/draft_order/remove_after_thirty_days/out_shopify_draft_order_vo.js
  shopify/flow/send_to_cognito_verification/mesa.json
  shopify/order/send_fulfillment_issue_to_slack_channel/mesa.json
  shopify/order/send_fulfillment_issue_to_slack_channel/out_orders_virtual_output.js
  shopify/order/send_to_cognito_verification/mesa.json
  shopify/order/send_to_cognito_verification/out_cognito_virtual_output.js
  shopify/order/send_to_fosdick_fulfillment/mesa.json
  shopify/order/send_to_fosdick_fulfillment/out_create_fosdick_order.js
  shopify/order/send_to_spa_ftp_file/mesa.json
  shopify/order/send_to_spa_ftp_file/out_orders_vo.js
Labels: QA'd

#211 Adding send_to_delighted_nps_survey template
  shopify/customer/add_email_to_klaviyo_list_with_tag/mesa.json
  shopify/order/add_created_tag_updated_tag/mesa.json
  shopify/order/lock_editing_with_tags/mesa.json
  tracktor/order/automatically_set_custom_status/mesa.json
  tracktor/order/send_to_delighted_nps_survey/mesa.json
Labels: QA'd, Ready to merge
