Repository shoppad/mesa-templates, pull requests merged in 2021-10, with the labels that each got.

#274 Create new version of shopify/order/add_line_item_properties_to_notes
  shopify/order/add_line_item_properties_to_notes/custom.js
  shopify/order/add_line_item_properties_to_notes/mesa.json
Labels: QA'd

#275 Update template: shopify/product/add_color_tag
  shopify/product/add_color_tag/mesa.json
  shopify/product/add_color_tag/out_add_shopify_product_tag.js
  shopify/product/add_image_colors_to_products_as_tags/mesa.json
Labels: QA'd

#276 Infinite Options: Send Product Bundles to Google Sheets
  infiniteoptions/order/add_product_bundle_to_google_sheet/custom.js
  infiniteoptions/order/add_product_bundle_to_google_sheet/mesa.json
Labels: QA'd, Ready to merge

#281 Enable 'Send Email Notification To Store Owner When Shopify Order Has Notes' by default
  shopify/order/send_email_notification_when_order_has_notes/mesa.json
Labels: Ready to merge
