Repository shoppad/mesa-templates, pull requests merged in 2021-05, with the labels that each got.

#213 Adding send_to_stampedio_review_request tracktor order template
  tracktor/order/send_to_stampedio_review_request/mesa.json
Labels: QA'd

#207 Add google_analytics template
  shopify/refund/google_analytics/custom.js
  shopify/refund/google_analytics/mesa.json
Labels: QA'd, Ready to merge

#206 Add automatically_publish template
  shopify/product/automatically_publish/mesa.json
Labels: QA'd, Ready to merge

#208 Send a Postcard When a Customer Places Their First Order
  shopify/order/send_postcard_to_customer_if_first_order/mesa.json
Labels: QA'd, Ready to merge

#204 Adding update_status_shipping_method template
  tracktor/order/update_status_shipping_method/mesa.json
Labels: QA'd

#203 Adding automatic_custom_status template
  tracktor/order/automatic_custom_status/mesa.json
Labels: QA'd

#214 Yotpo Loyalty Points Earned to Update Omnisend Contact template
  yotpoloyalty/customer_points/sent_to_omnisend_contact/mesa.json
Labels: QA'd, Ready to merge

#216 Yotpo Loyalty to Omnisend template: fix path
  yotpoloyalty/customer_points/send_to_omnisend_contact/mesa.json
Labels: Ready to merge

#217 Adding tracktor/order/send_to_google_sheets template
  tracktor/order/send_to_google_sheets/custom.js
  tracktor/order/send_to_google_sheets/mesa.json
Labels: QA'd

#218 Add shopify/order/add_free_product_when_customer_tagged template
  shopify/order/add_free_product_when_customer_tagged/mesa.json
Labels: QA'd, Ready to merge

#219 Salesforce template fixes
  shopify/customer/send_to_salesforce_account/mesa.json
  shopify/order/send_to_salesforce_opportunity_and_opportunity_products/mesa.json
  shopify/order/send_to_salesforce_opportunity_and_opportunity_products/salesforce_create_opportunity_product_transform.js
  shopify/product/send_to_salesforce_product_and_pricebook_entry/mesa.json
Labels: Work in progress

#220 Send a Discord invitation to a customer when they purchase a tagged product using Infinite Options
  infiniteoptions/order/send_discord_invite_via_email/README.md
  infiniteoptions/order/send_discord_invite_via_email/mesa.json
Labels: QA'd
