Repository shoppad/mesa-templates, pull requests merged in 2021-03, with the labels that each got.

#174 Add shopify_high_risk_order_send_to_slack template
  shopify/order/send_high_risk_orders_to_slack/mesa.json
Labels: Ready to merge

#183 Add shopify_product_inventory_updated_to_slack template
  shopify/product/send_slack_message_inventory_low/custom.js
  shopify/product/send_slack_message_inventory_low/mesa.json
Labels: Ready to merge

#182 Add shopify_customer_created_to_klaviyo_subscribe_list template
  shopify/customer/add_email_to_klaviyo_list/mesa.json
Labels: Ready to merge

#196 Uploadery to google sheets: Clean up tokens
  uploadery/order/add_line_items_to_google_sheet/mesa.json
Labels: Ready to merge

#186 Adding add_line_item_tag_to_order_after_order_creation template
  infiniteoptions/order/date_field_add_tag/mesa.json
Labels: Ready to merge

#188 Adding add_tags_of_tracktor_latest_delivery_status template
  tracktor/order/add_tag_with_current_delivery_status/mesa.json
Labels: Ready to merge

#189 Adding copy_product_tag_to_order_tag_when_order_created template
  shopify/order/add_product_tag/mesa.json
Labels: Ready to merge

#184 Add order_created_delay_to_tracktor_update_manual_status_order_send_email template
  tracktor/order/automatically_set_custom_status/mesa.json
  tracktor/order/enable_automatic_carrier_updates/mesa.json
  tracktor/order/update_custom_status_email_enable_automatic_carrier_collection/mesa_collection.json
Labels: Ready to merge

#197 Add uploadery/order/add_line_items_to_airtable template
  uploadery/order/add_line_items_to_airtable/README.md
  uploadery/order/add_line_items_to_airtable/mesa.json
Labels: QA'd

#198 Move tracktor custom status collection
  tracktor/order/automatically_set_custom_status_and_enable_automatic_carrier_updates/mesa_collection.json
Labels: Ready to merge

#190 Adding mesa forms
  form/contact_form/mesa.json
  form/customer_dob/README.md
  form/customer_dob/mesa.json
  form/shopify_order_return/README.md
  form/shopify_order_return/mesa.json
Labels: Ready to merge

#193 Adding add-remove-tag-shopify-customer-with-recharge-purchase templates
  recharge/order/add_shopify_customer_tag/mesa.json
  recharge/order/when_cancelled_remove_shopify_customer_tag/mesa.json
Labels: Ready to merge

#194 Adding send_email_to_customer_when_package_is_in_transit template
  tracktor/order/send_email_when_in_transit/mesa.json
Labels: Ready to merge

#187 Schedule Theme Change
  shopify/theme/schedule_change/mesa.json
Labels: Ready to QA
