Repository shoppad/mesa-templates, pull requests merged in 2021-09, with the labels that each got.

#263 Add template: form/send_to_gatsby
  form/send_to_gatsby/mesa.json
Labels: Ready to QA

#264 Add shopify/order/create_google_sheet template
  shopify/order/create_google_sheet/mesa.json
Labels: QA'd, Ready to merge

#266 Add shopify/customer/tag_customer_vip template
  shopify/customer/tag_customer_vip/mesa.json
Labels: QA'd, Ready to merge

#267 Fix / tag customers with edu email
  shopify/customer/tag_customers_with_edu_email/mesa.json
Labels: Ready to merge

#268 Enable "Add Line Item Properties to Order Notes" by default
  shopify/order/add_line_item_properties_to_notes/mesa.json
Labels: Ready to merge

#271 Add_Placeholder_Image
  shopify/product/add_placeholder_image/mesa.json
Labels: QA'd

#269 send_postcard_when_order_delivered
  tracktor/order/send_postcard_when_order_delivered/mesa.json
Labels: QA'd, Ready to merge

#270 send_discord_message_when_tagged
  shopify/order/send_discord_message_when_tagged/mesa.json
Labels: QA'd, Ready to merge
