Repository shoppad/mesa-templates, pull requests merged in 2022-11, with the labels that each got.

#387 Create a unique discount code for new customers template: Remove filter step and reduce to 20% discount
  shopify/customer/create_discount_code_for_new_customers/mesa.json
Labels: Ready to merge

#379 Update Slack templates to use v2 of connector
  bold/subscription/send_notification_on_subscription_product_change/mesa.json
  form/contact_form/mesa.json
  form/shopify_order_return/mesa.json
  infiniteoptions/order/send_discord_message/mesa.json
  returnly/return/send_to_slack/mesa.json
  shopify/order/send_high_risk_orders_to_slack/mesa.json
  shopify/order/send_international_orders_to_slack/mesa.json
  shopify/order/send_order_paid_message_to_slack/mesa.json
  shopify/product/send_slack_message_inventory_low/mesa.json
  tests/shopify_order_created_to_email/mesa.json
  tests/template_collection_test/shopify_order_created_to_email/mesa.json
Labels: Work in progress

#388 Slack: Remove lingering v1 tags
  bold/subscription/send_notification_on_subscription_product_change/mesa.json
  form/contact_form/mesa.json
  form/shopify_order_return/mesa.json
  infiniteoptions/order/send_slack_notification/mesa.json
  returnly/return/send_to_slack/mesa.json
  shopify/order/send_high_risk_orders_to_slack/mesa.json
  shopify/order/send_international_orders_to_slack/mesa.json
  shopify/order/send_order_paid_message_to_slack/mesa.json
  shopify/product/send_slack_message_inventory_low/mesa.json
Labels: Ready to merge

#390 Update pull_request_template.md file
  pull_request_template.md
Labels: Ready to merge

#391 Add template: Create a unique discount code for new customers to apply towards their next order
  shopify/customer/create_discount_code_for_new_customers_order/mesa.json
Labels: QA'd, Ready to merge

#393 Update Filter step in Tag an order when expedited shipping is selected template
  shopify/order/send_expedited_shipping_alert_to_logistics/filter.js
  shopify/order/send_expedited_shipping_alert_to_logistics/mesa.json
Labels: Ready to merge
