Repository shoppad/mesa-templates, pull requests merged in 2022-06, with the labels that each got.

#347 Update Send a postcard when an order is delivered template
  tracktor/fulfillment/send_postcard_when_order_delivered/mesa.json
  tracktor/order/send_postcard_when_order_delivered/mesa.json
Labels: QA'd

#348 Update templates with mapping steps
  delighted/survey/tag_shopify_customer_if_low_delighted_survey_score/README.md
  delighted/survey/tag_shopify_customer_if_low_delighted_survey_score/mesa.json
  form/shopify_order_return/README.md
  form/shopify_order_return/mesa.json
  shopify/customer/send_to_salesforce_account/mesa.json
  shopify/customer/tag_vip_customers/mesa.json
  shopify/order/add_customers_orders_to_notes/mesa.json
  shopify/order/flag_order_risk_if_no_price/README.md
  shopify/order/flag_order_risk_if_no_price/mesa.json
  shopify/order/send_expedited_shipping_alert_to_logistics/mesa.json
Labels: QA'd, Ready to merge

#352 Add Tag an order when a subscription is purchased template
  recharge/order/tag_order_when_subscription_purchased/mesa.json
Labels: QA'd, Ready to merge

#354 remove old send_to_cognito_verification template
  shopify/flow/send_to_cognito_verification/README.md
  shopify/flow/send_to_cognito_verification/examples/CognitoVerification.flow
  shopify/flow/send_to_cognito_verification/examples/mesa.json
  shopify/flow/send_to_cognito_verification/in_shopify_flow_order.js
  shopify/flow/send_to_cognito_verification/mesa.json
  shopify/flow/send_to_cognito_verification/out_cognito_verification.js
  shopify/flow/send_to_cognito_verification/out_cognito_virtual_output.js
  shopify/flow/send_to_cognito_verification/out_update_shopify_order_notes.js
Labels: Ready to merge
