Repository shoppad/mesa-templates, pull requests merged in 2022-08, with the labels that each got.

#368 Fix names of actions in templates
  form/yotpo_loyalty_customer_dob/mesa.json
  shopify/order/edit_add_product/mesa.json
Labels: Ready to merge

#369 Updating Recharge "Add a free product..." templates & Shopify SMS order risk template
  recharge/order/add_free_product_to_order_customer_tag/mesa.json
  recharge/order/add_free_product_to_upcoming_order/mesa.json
  shopify/order/send_high_risk_orders_to_sms/mesa.json
Labels: QA'd, Ready to merge

#370 Fix action steps names
  infiniteoptions/order/send_discord_message/mesa.json
  infiniteoptions/order/track_klaviyo_event/mesa.json
  infiniteoptions/order/yotpo_loyalty_set_birthday/mesa.json
  shopify/order/add_loyaltylion_points/mesa.json
  shopify/order/manually_approve_funds_capture/mesa.json
  shopify/order/send_discord_message_when_tagged/mesa.json
Labels: Ready to merge

#372 Update template steps to current versions
  bold/subscription/send_notification_on_subscription_product_change/mesa.json
  bold/subscription/send_notification_on_subscription_product_change/transform.js
  shopify/order/add_currency_to_order_tags/mesa.json
  shopify/order/add_shipping_province_tag/mesa.json
Labels: QA'd, Ready to merge

#371 Updating old MESA templates
  infiniteoptions/order/yotpo_loyalty_set_birthday/mesa.json
  recharge/order/send_renewal_to_google_analytics/mesa.json
  shopify/customer/add_email_to_klaviyo_list/mesa.json
  shopify/draft_order/send_email_notification/mesa.json
  shopify/order/manually_approve_funds_capture/custom.js
  shopify/order/manually_approve_funds_capture/mesa.json
  shopify/order/send_digital_download/mesa.json
  shopify/order/send_international_orders_to_slack/README.md
  shopify/order/send_international_orders_to_slack/mesa.json
  shopify/product/update_when_out_of_stock/mesa.json
  tracktor/order/send_to_google_sheets/mesa.json
Labels: QA'd

#373 Updating "Send a Discord invitation.." template and custom code's descriptions #373
  infiniteoptions/order/send_discord_invite_via_email/README.md
  infiniteoptions/order/send_discord_invite_via_email/mesa.json
  shopify/product/send_slack_message_inventory_low/mesa.json
  shopify/refund/google_analytics/mesa.json
Labels: Ready to merge

#374 Update "Send a Discord invitation when a product using Infinite Options is purchased" email's token
  infiniteoptions/order/send_discord_invite_via_email/mesa.json
Labels: Ready to merge

#375 Updating "Add "Order Can Be Edited" tag"... template
  shopify/order/lock_editing_with_tags/mesa.json
Labels: QA'd

#376 Fix name of Mailchimp action in a template
  shopify/customer/add_email_to_mailchimp_list/mesa.json
Labels: Ready to merge
