Repository shoppad/mesa-templates, pull requests merged in 2022-05, with the labels that each got.

#319 Publishing Add a free product to your customer's upcoming order template
  recharge/order/add_free_product_to_upcoming_order/mesa.json
Labels: Ready to merge

#323 Add template: Update an address in Recharge when a customer is created in Shopify
  recharge/customer/update_address_when_customer_created/mesa.json
Labels: QA'd, Ready to merge

#322 Add template: Add a free product to an upcoming order when a tag is added to the customer
  recharge/order/add_free_product_to_order_customer_tag/mesa.json
Labels: QA'd, Ready to merge

#317 Updating Cancel high-risk orders template
  shopify/order/cancel_high_risk_orders/mesa.json
Labels: QA'd

#327 Enabling Cancel high-risk orders template
  shopify/order/cancel_high_risk_orders/mesa.json
Labels: Ready to merge

#330 Update template: Send Shopify order and customer details to Odoo
  shopify/order/send_order_customer_details_to_odoo/custom.js
  shopify/order/send_order_customer_details_to_odoo/filter.js
  shopify/order/send_order_customer_details_to_odoo/filter_1.js
  shopify/order/send_order_customer_details_to_odoo/mesa.json
  shopify/order/send_order_customer_details_to_odoo/transform_mapping.js
  shopify/order/send_order_customer_details_to_odoo/transform_mapping_2.js
  shopify/order/send_order_customer_details_to_odoo/transformmapping.js
Labels: Ready to merge

#334 Updating Update a custom order status in Tracktor and send an email if "Express" shipping is enabled template
  tracktor/order/update_status_shipping_method/mesa.json
Labels: QA'd

#331 Updating Send an email when a package is "In Transit" template
  tracktor/fulfillment/send_email_when_in_transit/mesa.json
  tracktor/order/send_email_when_in_transit/mesa.json
Labels: QA'd

#321 HubSpot: v3 template updates
  hubspot/contact/send_to_shopify_customer/custom.js
  hubspot/contact/send_to_shopify_customer/custom_filter.js
  hubspot/contact/send_to_shopify_customer/mesa.json
  hubspot/contact/send_to_shopify_customer/shopify_api_customer_1_transform_js.js
  hubspot/contact/send_to_shopify_customer/shopify_api_customer_transform_js.js
  shopify/customer/send_to_hubspot_contact/mesa.json
  shopify/customer/send_to_hubspot_contact_and_mark_as_opportunity/mesa.json
  shopify/customer/send_to_hubspot_deal/hubspot_deal_transform.js
  shopify/customer/send_to_hubspot_deal/mesa.json
  shopify/customer/send_to_hubspot_deal/transform.js
  shopify/draft_order/send_to_hubspot_deal/mesa.json
  shopify/draft_order/send_to_hubspot_deal/transform.js
  shopify/order/send_to_hubspot_deal/mesa.json
Labels: QA'd

#337 Dont enable templates by default
  google_sheets/products/update_titles_on_shopify_products/mesa.json
  infiniteoptions/order/send_email/mesa.json
  recharge/order/tag_first_time_recharge_subscription_orders/mesa.json
  shopify/customer/tag_customers_with_edu_email/mesa.json
  shopify/customer/tag_vip_customers/mesa.json
  shopify/draft_order/remove_after_thirty_days/mesa.json
  shopify/flow/send_to_custom_code/mesa.json
  shopify/order/add_customers_orders_to_notes/mesa.json
  shopify/order/add_line_item_properties_to_notes/mesa.json
  shopify/order/add_payment_gateway_tag/mesa.json
  shopify/order/add_product_tag/mesa.json
  shopify/order/cancel_high_risk_orders/mesa.json
  shopify/order/remove_background_from_uploadery_images/mesa.json
  shopify/order/send_email_notification_when_order_has_notes/mesa.json
  shopify/order/send_expedited_shipping_alert_to_logistics/mesa.json
  shopify/order/send_high_risk_orders_to_sms/mesa.json
  shopify/order/send_order_report_card_email/mesa.json
  shopify/product/add_color_tag/mesa.json
  shopify/product/automatically_publish/mesa.json
  shopify/product/send_email_when_product_goes_out_of_stock/mesa.json
  shopify/product/update_when_out_of_stock/mesa.json
  spa/fulfillment/send_to_shopify/mesa.json
  tests/kitchen_sink/mesa.json
  tests/shopify_order_created_to_email/mesa.json
  tests/shopify_product_update/mesa.json
  tests/shopify_tokens/mesa.json
  tests/template_collection_test/shopify_order_created_to_email/mesa.json
  tests/template_collection_test/shopify_tokens/mesa.json
  tracktor/fulfillment/delay_in_transit_email/mesa.json
  tracktor/fulfillment/delay_in_transit_sms/mesa.json
  tracktor/fulfillment/send_email_when_in_transit/mesa.json
  tracktor/order/add_tag_with_current_delivery_status/mesa.json
  tracktor/order/enable_automatic_carrier_updates/mesa.json
  tracktor/order/send_sms_when_order_delivered/mesa.json
  tracktor/trackings/send_notification_on_change/mesa.json
  yotpo/review/create_gorgias_ticket/mesa.json
Labels: Ready to merge

#340 Salesforce: Remove local fields
  shopify/order/send_to_salesforce_contact/mesa.json
  shopify/order/send_to_salesforce_lead/mesa.json
Labels: Ready to merge

#342 Update Send Salesforce Lead To Shopify Customer template
  salesforce/lead/send_to_shopify_customer/mesa.json
  salesforce/lead/send_to_shopify_customer/output.js
  salesforce/lead/send_to_shopify_customer/transform.js
Labels: QA'd

#324 Updating Send an email if a package hasn't been delivered template
  tracktor/fulfillment/email_when_package_takes_too_long/mesa.json
  tracktor/order/email_when_package_takes_too_long/README.md
  tracktor/order/email_when_package_takes_too_long/mesa.json
Labels: QA'd

#333 Updating Send an SMS message to your customer when their order arrives template
  tracktor/fulfillment/send_sms_when_order_delivered/mesa.json
  tracktor/order/send_sms_when_order_delivered/mesa.json
Labels: QA'd

#329 Updating Delay custom order status updates template
  tracktor/fulfillment/automatically_set_custom_status/mesa.json
  tracktor/order/automatically_set_custom_status/mesa.json
Labels: QA'd

#326 Updating Tag orders with delivery status template
  tracktor/fulfillment/add_tag_with_current_delivery_status/mesa.json
  tracktor/order/add_tag_with_current_delivery_status/mesa.json
Labels: QA'd, Ready to merge

#339 Updating Mesa Twilio templates
  tracktor/fulfillment/delay_in_transit_twilio_sms/README.md
  tracktor/fulfillment/delay_in_transit_twilio_sms/mesa.json
  tracktor/fulfillment/send_twilio_sms_when_order_delivered/mesa.json
  tracktor/order/send_twilio_sms_when_order_delivered/mesa.json
Labels: QA'd, Ready to merge

#343 Add Tag an order when processed with Recharge
  recharge/order/tag_order_when_processed_with_recharge/mesa.json
Labels: QA'd

#341 Add Send an updated address to Recharge when a Shopify Customer is up…
  recharge/customer/update_address_when_customer_updated/mesa.json
Labels: QA'd

#335 Update Mesa Segment templates
  shopify/order/send_track_to_segment/mesa.json
  tracktor/fulfillment/send_track_to_segment/mesa.json
Labels: QA'd, Ready to merge

#336 Updating Automatically send Delighted NPS surveys to customers after their order is delivered template
  tracktor/fulfillment/send_to_delighted_nps_survey/mesa.json
  tracktor/order/send_to_delighted_nps_survey/mesa.json
Labels: QA'd, Ready to merge

#344 Updating Send a Shopify order status update to Segment template description
  shopify/order/send_track_to_segment/mesa.json
Labels: Ready to merge
