Repository shoppad/mesa-templates, pull requests merged in 2022-12, with the labels that each got.

#394 Recharge: Update names of steps in templates
  recharge/customer/update_address_when_customer_created/mesa.json
  recharge/customer/update_address_when_customer_updated/mesa.json
Labels: Ready to merge

#396 Updating Schedule a Shopify theme change on a specific date and time template
  shopify/theme/schedule_change/mesa.json
Labels: Ready to merge

#398 Shopify: Add Filter rule in Add a color tag to a product template
  shopify/product/add_color_tag/mesa.json
Labels: QA'd

#397 Google Analytics UA: Add version to Google Analytics steps
  recharge/order/send_renewal_to_google_analytics/mesa.json
  shopify/refund/google_analytics/mesa.json
Labels: Ready to merge

#399 Add template: Send a $20 gift card to a customer if they spend $100 or more
  shopify/order/send_gift_card_for_orders_over_100/mesa.json
Labels: QA'd, Ready to merge

#400 Add template: Send a gift card to a customer if their order is delayed
  gorgias/ticket/send_gift_card_when_order_delayed/mesa.json
Labels: QA'd, Ready to merge
