Repository shoppad/mesa-templates, pull requests merged in 2022-07, with the labels that each got.

#356 Updating Track Shopify refunds in Google Analytics template
  shopify/refund/google_analytics/custom.js
  shopify/refund/google_analytics/mesa.json
Labels: QA'd

#359 Shopify Booster Pack: Rename to pack folder
  pack/shopify_booster_pack/mesa_collection.json
Labels: Ready to merge

#364 Updating 2 Recharge customer templates
  recharge/customer/update_address_when_customer_created/mesa.json
  recharge/customer/update_customer_details/custom_1.js
  recharge/customer/update_customer_details/custom_2.js
  recharge/customer/update_customer_details/mesa.json
Labels: Ready to merge

#365 Adding Send files from a Shopify order to Dropbox template
  shopify/order/send_file_to_dropbox/mesa.json
Labels: QA'd, Ready to merge

#367 Update template name, description, and enable logging to match the dashboard
  blogstudio/article/send_to_another_store/mesa.json
  bold/subscription/send_notification_on_new_subscription/mesa.json
  bold/subscription/send_notification_on_subscription_product_change/mesa.json
  delighted/survey/low_score_email_staff/mesa.json
  form/send_quote/mesa.json
  form/start_return_with_gorgias_ticket/mesa.json
  form/yotpo_loyalty_customer_dob/mesa.json
  infiniteoptions/order/send_discord_invite_via_email/mesa.json
  infiniteoptions/order/send_discord_message/mesa.json
  infiniteoptions/order/track_klaviyo_event/mesa.json
  infiniteoptions/order/yotpo_loyalty_set_birthday/mesa.json
  pagestudio/page/send_to_another_store/mesa.json
  returnly/return/send_to_slack/mesa.json
  shopify/customer/add_email_to_klaviyo_list/mesa.json
  shopify/customer/add_email_to_mailchimp_list/mesa.json
  shopify/customer/add_to_google_sheets_document/mesa.json
  shopify/customer/send_to_omnisend_contact/mesa.json
  shopify/customer/tag_customer_vip/mesa.json
  shopify/draft_order/send_email_notification/mesa.json
  shopify/order/add_currency_to_order_tags/mesa.json
  shopify/order/add_loyaltylion_points/mesa.json
  shopify/order/add_shipping_province_tag/mesa.json
  shopify/order/approve_thank_you_email/mesa.json
  shopify/order/lock_editing_with_tags/mesa.json
  shopify/order/manually_approve_funds_capture/mesa.json
  shopify/order/send_digital_download/mesa.json
  shopify/order/send_discord_message_when_tagged/mesa.json
  shopify/order/send_email_to_loyaltylion_customer_if_rewards_not_used/mesa.json
  shopify/order/send_international_orders_to_slack/mesa.json
  shopify/order/send_order_paid_message_to_slack/mesa.json
  shopify/order/send_order_report_card_email/mesa.json
  shopify/order/send_postcard_to_customer_if_first_order/mesa.json
  shopify/order/send_tax_receipt_for_charitable_donations/mesa.json
  shopify/order/send_to_delighted_nps_survey/mesa.json
  shopify/order/subscribe_shoppers_to_klaviyo_list/mesa.json
  shopify/product/add_to_etsy_listing/mesa.json
  shopify/product/create_facebook_product/mesa.json
  shopify/product/send_slack_message_inventory_low/mesa.json
  stamped_io/review/send_negative_review_to_customer_email/mesa.json
  tiktok/reports/send_daily_adgroup_summary_report/mesa.json
  uploadery/order/add_line_items_to_airtable/mesa.json
  yotpo/review/create_gorgias_ticket/mesa.json
  yotpoloyalty/customer_points/send_to_omnisend_contact/mesa.json
Labels: Ready to merge
