Repository shoppad/mesa-templates, pull requests merged in 2023-06, with the labels that each got.

#463 Add template setup round 3
  infiniteoptions/order/send_discord_invite_via_email/mesa.json
  infiniteoptions/order/send_discord_message/README.md
  infiniteoptions/order/send_discord_message/mesa.json
  infiniteoptions/order/send_slack_notification/mesa.json
  tracktor/fulfillment/automatically_set_custom_status/mesa.json
  tracktor/fulfillment/send_track_to_segment/mesa.json
Labels: Ready to merge

#464 Fix template setup
  tracktor/fulfillment/automatically_set_custom_status/mesa.json
Labels: Ready to merge

#466 Add template: Send Etsy orders to Google Sheets
  etsy/order/send_to_google_sheets/mesa.json
Labels: QA'd, Ready to merge

#467 Uploadery: Add template onboarding support
  uploadery/order/add_line_items_to_google_sheet/mesa.json
Labels: QA'd

#465 Delay v2 launch: specify version as v1
  gorgias/ticket/send_gift_card_when_order_delayed/mesa.json
  shopify/draft_order/remove_after_thirty_days/mesa.json
  shopify/order/lock_editing_with_tags/mesa.json
  shopify/order/send_email_to_loyaltylion_customer_if_rewards_not_used/mesa.json
  shopify/order/send_gift_card_for_orders_over_100/mesa.json
  shopify/order/send_thanks_io_postcard/mesa.json
  shopify/order/send_to_delighted_nps_survey/mesa.json
  shopify/product/add_and_remove_tags_on_new_products/mesa.json
  stamped_io/review/send_negative_review_to_customer_email/mesa.json
  tracktor/fulfillment/automatically_set_custom_status/mesa.json
  tracktor/fulfillment/delay_in_transit_email/mesa.json
  tracktor/fulfillment/delay_in_transit_sms/mesa.json
  tracktor/fulfillment/delay_in_transit_twilio_sms/mesa.json
  tracktor/fulfillment/email_when_package_takes_too_long/mesa.json
  tracktor/fulfillment/send_to_delighted_nps_survey/mesa.json
  tracktor/fulfillment/send_to_stampedio_review_request/mesa.json
  tracktor/order/refund_shipping_cost/mesa.json
Labels: Ready to QA
