Repository shoppad/mesa-templates, pull requests merged in 2023-03, with the labels that each got.

#420 Update templates that reference order_spend
  shopify/order/add_customers_orders_to_notes/mesa.json
  shopify/order/add_free_product_to_new_customer_first_order/mesa.json
  shopify/order/send_postcard_to_customer_if_first_order/mesa.json
Labels: QA'd

#424 Update 2 templates to use the Delay variables
  shopify/order/send_gift_card_for_orders_over_100/mesa.json
  shopify/order/send_to_delighted_nps_survey/mesa.json
Labels: Ready to merge

#422 Update Add a placeholder image when a Shopify product is created template
  shopify/product/add_placeholder_image/mesa.json
Labels: QA'd, Ready to merge

#423 Update Automatically publish a product if it has an image and description template
  shopify/product/automatically_publish/mesa.json
Labels: QA'd, Ready to merge

#425 Fix variable in the Receive an email when a product goes out of stock template
  shopify/product/send_email_when_product_goes_out_of_stock/mesa.json
Labels: QA'd, Ready to merge

#427 Updating Shopify templates
  shopify/customer/backorder_tag_to_klaviyo_email_list/mesa.json
  shopify/draft_order/send_to_hubspot_deal/mesa.json
  shopify/order/cancel_high_risk_orders/mesa.json
  shopify/order/send_expedited_shipping_alert_to_logistics/filter.js
  shopify/order/send_expedited_shipping_alert_to_logistics/mesa.json
  shopify/product/slack_message_when_product_goes_out_of_stock/mesa.json
Labels: QA'd, Ready to merge
